### ISSUE TITLE
No exiting to main menu from gameplay

### ISSUE THREAD

**Issue by PiotrEredin** [Sulfastic/AMSI-project#15]
I realized that we didn't create a story to exit from gameplay at any time (basically didn't think of the "ESC" function) to the main menu.
We could fix this in two ways:
1. Create the story in question
or
2. Assume that this is a haunted house scenario, and the only way for the player to exit the house is to either kill all presences or die :)

What do you think?

**Comment by Sulfastic** [comment]
I like the second one 👍
