### ISSUE TITLE
Yeoman

### ISSUE THREAD

**Issue by PiotrEredin** [Sulfastic/AMSI-project#8]
I'm struggling to get yeoman to work.
It gives an error when trying "npm run build".
It doesn't execute when not built (yes, I've started "npm start").

I've researched phaser, and the library itself is pretty powerful and I think that we could use it instead of yeoman with no problems.

What do You think?

**Comment by Sulfastic** [comment]
Why would you use yeoman now? I used it only once to generate dummy working project with configured enviroment; for now it is useless. If you want to run project, you should run in root:
npm install
npm start

after the process you should be able to run it by typing in browser:
http://localhost:<provided by npm start port, e.g: 12345>

if you want to run it in desktop window, type:
npm run build

after the process completes, go to the cmd-build and double click the .bat file; after a while you should find executable file in output -> build (and deeperm I can't remeber right now)

**Comment by PiotrEredin** [comment]
Now the browser only types: {"tinylr":"Welcome","version":"0.2.1"} on blank page, is it normal?

...and the build command crushes, saying that this: "rm -rf build" fails. Could you help? What am I doing wrong?
